[build]
  publish = "build/web"
  command = "flutter build web --release --base-href /"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/flutter.js"
    [headers.values]
    Cache-Control = "public, max-age=3600, immutable"

[[headers]]
  for = "/main.dart.js"
    [headers.values]
    Cache-Control = "public, max-age=3600, immutable"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 